# Generated by Django 4.2 on 2023-04-23 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count_of_questions', models.PositiveIntegerField()),
                ('count_of_subjects', models.PositiveIntegerField(default=1)),
                ('desc', models.TextField()),
                ('answers', models.CharField(max_length=95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('file_of_questions', models.FileField(default=None, upload_to='questions/')),
                ('language', models.TextField(choices=[("o'zbek", 'Uz'), ('rus', 'Ru'), ('ingliz', 'Eng'), ('qoraqalpoq', 'Kar')], default="o'zbek")),
                ('level', models.TextField(choices=[('oson', 'Easy'), ("o'rta", 'Medium'), ('qiyin', 'Hard')], default="o'rta")),
                ('point', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='TestScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count_of_questions', models.PositiveIntegerField(default=0)),
                ('count_of_correct_answers', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exam.test')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
