# Generated by Django 4.2 on 2023-05-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(height_field=150, null=True, upload_to='avatars', width_field=150),
        ),
    ]
