# Generated by Django 4.2 on 2023-05-22 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatars/default_user.png', null=True, upload_to='avatars'),
        ),
    ]
